#!/usr/bin/env python3
"""Build index.html from the files in src/.

    python build.py            write index.html
    python build.py --check    exit 1 if index.html is not what the sources produce (used by CI)

The page stays a single self-contained file - no external scripts or styles, so it opens from a disk,
GitHub Pages or the Docker image alike - but it is written as small files:

    src/head.html        <head> contents before the stylesheet (meta tags, CSP, favicon placeholder)
    src/logo.svg         the logo: inlined in the sidebar and used as the favicon
    src/icon-*.png       PNG fallbacks for the favicon (made by tools/make-icons.py)
    src/style.css        the stylesheet
    src/body.html        the page skeleton
    src/engine/*.js      calculations, data model, storage (no page code)
    src/ui/*.js          pages, shell and start-up, in the order they must run
    demo/…               the example household, embedded as DEMO_YEAR_JSON
    tests/maths.test.js  the maths tests; tests/run.html (written here) runs them in a browser,
                         tests/run.js runs them in Node

Files in src/engine and src/ui are joined in file-name order, which is why they carry number prefixes:
the scripts share one scope, and the order is the order they run in. Standard library only.
"""
import base64
import json
import os
import re
import sys
from urllib.parse import quote

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, 'src')
OUT = os.path.join(ROOT, 'index.html')


def read(*parts):
    with open(os.path.join(*parts), encoding='utf-8', newline='') as f:
        return f.read().replace('\r\n', '\n')          # checked out with CRLF on Windows? build the same bytes anyway


def scripts(folder):
    names = sorted(n for n in os.listdir(os.path.join(SRC, folder)) if n.endswith('.js'))
    return [(n, read(SRC, folder, n)) for n in names]


def js_string(text):
    """A JavaScript string literal for text: JSON is valid JS, and ensure_ascii keeps the output plain ASCII."""
    # never let the text close the <script> block, or open an HTML comment (which changes how a parser reads script text)
    return json.dumps(text, ensure_ascii=True).replace('</', '<\\/').replace('<!--', '<\\!--')


def embed(code):
    """Fill the placeholder that stands for the example household, which is kept outside src/."""
    demo = os.path.join(ROOT, 'demo', 'example-household-2026.json')
    if '/*@DEMO_YEAR_JSON*/' in code:
        data = json.loads(read(demo))['data']
        code = code.replace('/*@DEMO_YEAR_JSON*/null', js_string(json.dumps(data, separators=(',', ':'), ensure_ascii=True)))
    return code


def logo_svg():
    """src/logo.svg with its comments and indentation squeezed out."""
    svg = re.sub(r'<!--.*?-->', '', read(SRC, 'logo.svg'), flags=re.S)
    svg = re.sub(r'\s+', ' ', svg)
    return re.sub(r'>\s+<', '><', svg).replace(' />', '/>').strip()


def logo_inline():
    """The logo as markup for the page: no size or label of its own (the page sizes it, the text beside it names it)."""
    opening, rest = logo_svg().split('>', 1)
    opening = re.sub(r' (xmlns|width|height|aria-label)="[^"]*"', '', opening)
    return opening + ' class="mark" aria-hidden="true" focusable="false">' + rest


def png_uri(name):
    with open(os.path.join(SRC, name), 'rb') as f:
        return 'data:image/png;base64,' + base64.b64encode(f.read()).decode('ascii')


def favicons():
    """PNG first for browsers that cannot do SVG, then the SVG, which the rest prefer. All inline: the CSP allows data: images only."""
    svg = 'data:image/svg+xml,' + quote(logo_svg().replace('"', "'"), safe="/:=,'-.")
    return ('<link rel="icon" type="image/png" sizes="64x64" href="%s">\n'
            '<link rel="icon" type="image/svg+xml" href="%s">\n'
            '<link rel="apple-touch-icon" href="%s">\n') % (png_uri('icon-64.png'), svg, png_uri('icon-180.png'))


def fill(text, placeholder, value):
    assert placeholder in text, 'no ' + placeholder + ' in the source to fill'
    return text.replace(placeholder, value)


def build():
    parts = [fill(read(SRC, 'head.html'), '<!--@FAVICONS-->\n', favicons()), '<style>\n', read(SRC, 'style.css'),
             '</style>\n</head>\n', fill(read(SRC, 'body.html'), '<!--@LOGO-->', logo_inline()), '<script>\n']
    for folder in ('engine', 'ui'):
        for name, code in scripts(folder):
            parts.append(embed(code) if code.endswith('\n') else embed(code) + '\n')
    parts.append('</script></body></html>\n')
    return ''.join(parts)


TEST_PAGE = os.path.join(ROOT, 'tests', 'run.html')

TEST_PAGE_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Penny Keeper - maths tests</title>
<!-- Generated by build.py from the files in src/engine. Open it in a browser; no server needed. -->
<style>
body{font:15px/1.5 system-ui,sans-serif;max-width:900px;margin:24px auto;padding:0 16px}
.ok{color:#2b7a30}.fail{color:#bf3a2e;font-weight:600}li{margin:3px 0}code{background:#eee;padding:0 4px}
</style>
</head>
<body>
<h1>Maths tests</h1>
<p id="summary">Running...</p>
<ul id="list"></ul>
@ENGINE@<script src="maths.test.js"></script>
<script>
const results = runMathsTests();
const failed = results.filter(r => !r.ok).length;
document.getElementById('summary').innerHTML = '<b class="' + (failed ? 'fail' : 'ok') + '">' + (results.length - failed) + ' of ' + results.length + ' passed</b>';
document.getElementById('list').innerHTML = results.map(r =>
  '<li class="' + (r.ok ? 'ok' : 'fail') + '">' + (r.ok ? 'ok' : 'FAIL') + ' - ' + r.name + (r.ok ? '' : '<br><code>' + r.error + '</code>') + '</li>').join('');
</script>
</body>
</html>
"""


def build_test_page():
    """tests/run.html: loads the engine files and the maths tests as plain scripts, so the same tests run in a browser."""
    tags = ''.join('<script src="../src/engine/%s"></script>\n' % name for name, _ in scripts('engine'))
    return TEST_PAGE_TEMPLATE.replace('@ENGINE@', tags)


def main():
    out = build()
    page = build_test_page()
    if '--check' in sys.argv:
        stale = [name for name, path, text in (('index.html', OUT, out), ('tests/run.html', TEST_PAGE, page))
                 if (read(path) if os.path.exists(path) else '') != text]
        if stale:
            sys.stderr.write('%s out of date with src/. Run: python build.py\n' % ' and '.join(stale))
            return 1
        print('index.html and tests/run.html are up to date (%d KB)' % (len(out.encode('utf-8')) // 1024))
        return 0
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(out)
    with open(TEST_PAGE, 'w', encoding='utf-8', newline='\n') as f:
        f.write(page)
    print('wrote index.html (%d KB, %d lines) and tests/run.html' % (len(out.encode('utf-8')) // 1024, out.count('\n')))
    return 0


if __name__ == '__main__':
    sys.exit(main())
