/* Maths tests for the calculation engine (src/engine). Plain script, no framework: it runs in the same scope as the
   engine, either in Node (tests/run.js, used by CI) or in a browser page (tests/run.html, generated by build.py).

   Figures marked "Revenue" are copied from revenue.ie's "Tax rates, bands and reliefs" chart and USC page, so a
   typing slip in src/engine/10-tax-data.js shows up here. Everything else is worked out by hand in the comment. */

function runMathsTests(){
  const results = [];
  const test = (name, fn) => {
    try{ fn(); results.push({name, ok:true}); }
    catch(e){ results.push({name, ok:false, error:e.message}); }
  };
  const near = (got, want, tol, label) => {
    tol = tol === undefined ? 0.01 : tol;
    if(!(Math.abs(got - want) <= tol)) throw new Error((label ? label + ': ' : '') + 'expected ' + want + ', got ' + (typeof got === 'number' ? +got.toFixed(4) : got));
  };
  const same = (got, want, label) => {
    if(JSON.stringify(got) !== JSON.stringify(want)) throw new Error((label ? label + ': ' : '') + 'expected ' + JSON.stringify(want) + ', got ' + JSON.stringify(got));
  };
  const person = o => Object.assign({id:'a', name:'T', gross:0, pensionPct:0, avcMonthly:0, bikMonthly:0, bonus:0,
    status:'single', srcop:44000, credits:[{name:'Personal Tax Credit', amount:2000}, {name:'Employee Tax Credit', amount:2000}]}, o);
  const fresh = year => { DB = {years:{}, ui:{}, netWorth:{assets:[], liabs:[], snaps:[]}, theme:'light'}; Y = blankYear(year || 2026); migrate(Y); return Y; };

  fresh(2026);
  const b26 = presetFor(2026);

  /* ---------------- Revenue's published figures, year by year ---------------- */
  const BANDS = {            // single, single parent, married one income, second-earner increase
    2022:[36800, 40800, 45800, 27800], 2023:[40000, 44000, 49000, 31000], 2024:[42000, 46000, 51000, 33000],
    2025:[44000, 48000, 53000, 35000], 2026:[44000, 48000, 53000, 35000]};
  Object.keys(BANDS).forEach(yr => test('Revenue standard rate bands ' + yr, () => {
    const p = presetFor(+yr), w = BANDS[yr];
    same([p.srcopSingle, p.srcopParent, p.srcopMax, p.srcopSecond], w);
  }));
  const USC = {              // cumulative upper limit of each band and its rate (Revenue USC page)
    2022:[[12012,.005],[21295,.02],[70044,.045]], 2023:[[12012,.005],[22920,.02],[70044,.045]],
    2024:[[12012,.005],[25760,.02],[70044,.04]],  2025:[[12012,.005],[27382,.02],[70044,.03]],
    2026:[[12012,.005],[28700,.02],[70044,.03]]};
  Object.keys(USC).forEach(yr => test('Revenue USC bands ' + yr, () => {
    const got = presetFor(+yr).uscBands.slice(0, 3).map(b => [b.to, b.rate]);
    same(got, USC[yr]);
    near(presetFor(+yr).uscBands[3].rate, 0.08, 1e-9, 'top rate');
  }));
  const CREDITS = {          // [single, married, employee, earned, home carer, SPCCC, rent single, rent couple] (Revenue)
    2022:[1700, 3400, 1700, 1700, 1600, 1650, 500, 1000], 2023:[1775, 3550, 1775, 1775, 1700, 1650, 500, 1000],
    2024:[1875, 3750, 1875, 1875, 1800, 1750, 1000, 2000], 2025:[2000, 4000, 2000, 2000, 1950, 1900, 1000, 2000],
    2026:[2000, 4000, 2000, 2000, 1950, 1900, 1000, 2000]};
  Object.keys(CREDITS).forEach(yr => test('Revenue credits ' + yr, () => {
    const y = +yr;
    same([creditAmount('single',y), creditAmount('married',y), creditAmount('employee',y), creditAmount('earned',y),
          creditAmount('homeCarer',y), creditAmount('spccc',y), creditAmount('rent',y), creditAmount('rentCouple',y)], CREDITS[yr]);
  }));
  test('Revenue credits that do not change by year', () => {
    [2022,2023,2024,2025,2026].forEach(y => {
      same([creditAmount('ageSingle',y), creditAmount('ageMarried',y), creditAmount('widowParent1',y), creditAmount('widowParent5',y)], [245, 490, 3600, 1800], 'year '+y);
    });
    same([creditAmount('widowNoChild',2026), creditAmount('incapChild',2026), creditAmount('depRelative',2026), creditAmount('blindSingle',2026), creditAmount('blindBoth',2026)], [2540, 3800, 305, 1950, 3900]);
  });
  test('Mortgage Interest Tax Credit: 1,250 for 2023-2025, 625 for 2026 (Revenue credit page)', () => {
    same([2022,2023,2024,2025,2026].map(y => creditAmount('mortInt', y)), [0, 1250, 1250, 1250, 625]);
  });
  test('2027 figures from the Budget summaries', () => {
    const p = presetFor(2027);
    same([p.srcopSingle, p.srcopMax, p.srcopParent, p.srcopSecond], [46500, 55500, 50500, 37500]);
    same([creditAmount('single',2027), creditAmount('rent',2027), creditAmount('rentCouple',2027), creditAmount('homeCarer',2027)], [2125, 1150, 2300, 2050]);
    near(p.uscBands[1].to, 30300, 0, 'USC 2% band'); near(p.prsiRate2, 0.045, 1e-9, 'PRSI from October');
  });
  test('a year with no figures uses the nearest one', () => {
    near(presetFor(2030).srcopSingle, 46500, 0); near(presetFor(2019).srcopSingle, 36800, 0);
  });
  test('every credit in the library is flagged for 2027 only when Revenue has not published it', () => {
    creditLibrary(2026).forEach(c => { if(c.est) throw new Error(c.name + ' is an estimate in 2026'); });
    if(!creditLibrary(2027).some(c => c.est)) throw new Error('expected some 2027 estimates');
  });

  /* ---------------- income tax, PRSI, USC ---------------- */
  test('single, 50,000, 2026', () => {
    // tax 44,000 x 20% + 6,000 x 40% = 11,200, less 4,000 credits = 7,200
    // USC 12,012 x 0.5% + 16,688 x 2% + 21,300 x 3% = 1,032.82
    // PRSI 50,000 x (9 months at 4.2% + 3 months at 4.35%) / 12 = 2,118.75
    const t = calcTax(person({gross:50000}), b26);
    near(t.paye, 7200); near(t.usc, 1032.82); near(t.prsi, 2118.75); near(t.net, 39648.43);
  });
  test('married, one income, 70,000: band 53,000 and the couple credit', () => {
    // tax 53,000 x 20% + 17,000 x 40% = 17,400, less (4,000 + 2,000) = 11,400
    const t = calcTax(person({gross:70000, status:'married1', srcop:53000, credits:[{name:'Personal Tax Credit', amount:4000}, {name:'Employee Tax Credit', amount:2000}]}), b26);
    near(t.paye, 11400);
  });
  test('two incomes share the couple\'s band: 70,000 and 30,000', () => {
    const A = person({id:'A', gross:70000, status:'married2'}), B = person({id:'B', gross:30000, status:'married2'});
    Y.people = [A, B];
    near(effectiveSrcop(A, b26), 53000, 0, 'higher earner');   // 44,000 + 9,000 of the 14,000 B cannot use
    near(calcTax(A, b26).paye, 53000*0.2 + 17000*0.4 - 4000, 0.01);
    near(calcTax(B, b26).paye, 30000*0.2 - 4000, 0.01);
  });
  test('two incomes that both fill their band keep one single band each', () => {
    const A = person({id:'A', gross:60000, status:'married2'}), B = person({id:'B', gross:50000, status:'married2'});
    Y.people = [A, B];
    near(effectiveSrcop(A, b26), 44000, 0); near(effectiveSrcop(B, b26), 44000, 0);
    near(calcTax(A, b26).paye + calcTax(B, b26).paye, (44000*.2 + 16000*.4 - 4000) + (44000*.2 + 6000*.4 - 4000), 0.01);
  });
  test('the couple\'s two bands never total more than twice the single band', () => {
    [[90000,44000],[90000,30000],[100000,10000],[45000,45000],[60000,0]].forEach(([a, b]) => {
      const A = person({id:'A', gross:a, status:'married2'}), B = person({id:'B', gross:b, status:'married2'});
      Y.people = [A, B];
      const used = Math.min(effectiveSrcop(A, b26), taxableOf(A)) + Math.min(effectiveSrcop(B, b26), taxableOf(B));
      if(used > 2*b26.srcopSingle + 0.001) throw new Error('bands used ' + used + ' for ' + a + '/' + b);
    });
  });
  test('a bonus that straddles the band is taxed at both rates', () => {
    // 40,000 + 10,000 bonus: 4,000 at 20% and 6,000 at 40% = 3,200
    near(calcTax(person({gross:40000, bonus:10000}), b26).bTax, 3200);
  });
  test('PRSI is not charged at or below the weekly threshold', () => {
    near(calcTax(person({gross:17000}), b26).prsi, 0);                                   // 326 a week
    near(calcTax(person({gross:18500}), b26).prsi, 18500 * (0.042*9/12 + 0.0435*3/12));  // 356 a week
  });
  test('USC: nothing at the exemption, then every band applies', () => {
    near(calcTax(person({gross:13000}), b26).usc, 0);
    near(calcTax(person({gross:13001}), b26).usc, 12012*0.005 + 989*0.02);
    near(calcTax(person({gross:80000}), presetFor(2024)).usc, 60.06 + 274.96 + 1771.36 + 796.48, 0.01, '2024 has a 4% band');
  });
  test('pension is relieved for income tax but not for USC or PRSI', () => {
    const t = calcTax(person({gross:50000, pensionPct:5}), b26);
    near(t.paye, (44000*.2 + 3500*.4) - 4000); near(t.usc, 1032.82);
  });
  test('benefit-in-kind is taxed but is not cash', () => {
    const t = calcTax(person({gross:50000, bikMonthly:500}), b26);
    near(t.grossPay, 56000); near(t.gross, 50000);
  });
  test('credits cannot make tax negative', () => { near(calcTax(person({gross:15000}), b26).paye, 0); });

  /* ---------------- credits that come back after the year ---------------- */
  test('rent credit is not in the monthly pay but comes back as a refund', () => {
    const base = calcTax(person({gross:50000}), b26);
    const withRent = calcTax(person({gross:50000, credits:[{name:'Personal Tax Credit', amount:2000}, {name:'Employee Tax Credit', amount:2000}, {name:'Rent Tax Credit', amount:1000}]}), b26);
    near(withRent.paye, base.paye, 0, 'monthly tax unchanged');
    near(withRent.netMonthly, base.netMonthly, 0, 'take-home unchanged');
    near(withRent.refund, 1000, 0.01, 'refund');
    near(withRent.credits, 4000, 0, 'credits in pay');
  });
  test('a refund credit cannot give back more tax than was paid', () => {
    const t = calcTax(person({gross:20000, credits:[{name:'Personal Tax Credit', amount:2000}, {name:'Employee Tax Credit', amount:2000}, {name:'Rent Tax Credit', amount:1000}]}), b26);
    near(t.paye, 0); near(t.refund, 0);
    const partly = calcTax(person({gross:23000, credits:[{name:'Personal Tax Credit', amount:2000}, {name:'Employee Tax Credit', amount:2000}, {name:'Rent Tax Credit', amount:1000}]}), b26);
    near(partly.paye, 600); near(partly.refund, 600, 0.01, 'only the 600 of tax actually paid comes back');
  });
  test('a credit row can be switched between pay and refund', () => {
    near(calcTax(person({gross:50000, credits:[{name:'Personal Tax Credit', amount:2000}, {name:'Rent Tax Credit', amount:1000, when:'pay'}]}), b26).credits, 3000);
    near(calcTax(person({gross:50000, credits:[{name:'Personal Tax Credit', amount:2000}, {name:'Home Carer Tax Credit', amount:1000, when:'refund'}]}), b26).refundCredits, 1000);
  });
  test('the credit library says which credits are refunds', () => {
    const refund = creditLibrary(2026).filter(c => c.when === 'refund').map(c => c.key).sort();
    same(refund, ['mortInt', 'rent', 'rentCouple']);
  });
  test('year-end refund adds credit refunds to health, remote working and tuition', () => {
    fresh(2026);
    Y.people = [person({gross:50000, credits:[{name:'Personal Tax Credit', amount:2000}, {name:'Employee Tax Credit', amount:2000}, {name:'Rent Tax Credit', amount:1000}]})];
    Y.reliefs.health = [{amount:500, refunded:100}];
    Y.reliefs.tuitionClaims = [{type:'full', fees:5000}];
    const E = yearEndRefund();
    near(E.creditsTotal, 1000); near(E.health, 80); near(E.tuition, 400); near(E.total, 1480);
  });

  /* ---------------- personal credit by situation ---------------- */
  test('personal credit follows the situation', () => {
    near(personalAmount('single', 2026), 2000); near(personalAmount('married', 2026), 4000); near(personalAmount('marriedHalf', 2026), 2000);
    near(personalAmount('widowNoChild', 2026), 2540); near(personalAmount('single', 2027), 2125);
    same([defaultPersonalType('single'), defaultPersonalType('parent'), defaultPersonalType('married1'), defaultPersonalType('married2')], ['single', 'single', 'married', 'marriedHalf']);
  });
  test('refreshCredits brings a person up to a year\'s credits', () => {
    const p = person({status:'married1', credits:[{name:'Personal Tax Credit', amount:1}, {name:'Employee Tax Credit', amount:1}, {name:'Rent Tax Credit', amount:1}, {name:'My own credit', amount:123}]});
    refreshCredits(p, 2027);
    same(p.credits.map(c => c.amount), [4250, 2125, 1150, 123]);
  });
  test('a personal credit that does not match the situation is flagged', () => {
    fresh(2026);
    const p = person({status:'married1', credits:[{name:'Personal Tax Credit', amount:2000}]});
    if(!personalCheck(p)) throw new Error('expected a warning');
    near(personalCheck(p).want, 4000);
    p.credits[0].amount = 4000;
    if(personalCheck(p)) throw new Error('did not expect a warning');
  });

  /* ---------------- tax-year housekeeping ---------------- */
  test('a saved year that differs from the built-in figures is detected', () => {
    const b = presetFor(2024);
    if(taxBandsDiffer(b, presetFor(2024))) throw new Error('same figures reported as different');
    b.uscBands[2].rate = 0.03;                  // the mistake an earlier version made
    if(!taxBandsDiffer(b, presetFor(2024))) throw new Error('a changed USC band was not noticed');
  });
  test('rate band status is guessed from a band', () => {
    same([guessStatus({srcop:44000}, b26), guessStatus({srcop:53000}, b26), guessStatus({srcop:48000}, b26), guessStatus({srcop:50000}, b26)], ['single', 'married1', 'parent', 'custom']);
  });
  test('migrate fills the fields a page reads, and is safe to run twice', () => {
    const y = {year:2026, people:[{name:'A', gross:40000}], bills:[], taxBands:presetFor(2026)};
    migrate(y);
    const once = JSON.stringify(y);
    migrate(y);
    same(JSON.stringify(y).length > 0 && Array.isArray(y.goals) && Array.isArray(y.reliefs.tuitionClaims) && y.people[0].status === 'single', true);
    same(JSON.stringify(y).replace(/"id":"[^"]+"/g, ''), once.replace(/"id":"[^"]+"/g, ''));
  });

  /* ---------------- bills, budget and the year ahead ---------------- */
  const billSet = () => [{id:'1', name:'Weekly', freq:'Weekly', amount:100, holder:'Joint', kind:'bill'},
    {id:'2', name:'Fortnightly', freq:'Fortnightly', amount:100, holder:'Joint', kind:'bill'}, {id:'3', name:'Monthly', freq:'Monthly', amount:100, holder:'Joint', kind:'bill'},
    {id:'4', name:'Quarterly', freq:'Quarterly', amount:100, holder:'Joint', kind:'bill'}, {id:'5', name:'Annual', freq:'Annual', amount:100, holder:'Joint', kind:'bill'}];
  test('bills convert to a year, a month and a week', () => {
    fresh(2026); Y.bills = billSet();
    same(Y.bills.map(annualOf), [5200, 2600, 1200, 400, 100]);
    const t = billTotals('bill');
    near(t.monthly, 9500/12); near(t.weekly, 9500/52);
  });
  test('year ahead: undated bills are spread evenly and add up to a year', () => {
    fresh(2026); Y.bills = billSet();
    const ya = yearAhead();
    near(ya.months[3].total, 9500/12); near(ya.months.reduce((s, m) => s + m.total, 0), 9500);
  });
  test('year ahead: a dated yearly bill lands once, a weekly bill about 52 times', () => {
    fresh(2026); Y.bills = billSet();
    Y.bills[4].nextDue = iso(addMonths(new Date(), 3)); Y.bills[0].nextDue = iso(new Date());
    const ya = yearAhead();
    same(ya.months.filter(m => m.items.some(i => i.name === 'Annual')).length, 1);
    const weeks = ya.months.reduce((s, m) => s + m.items.filter(i => i.name === 'Weekly').reduce((q, i) => q + i.count, 0), 0);
    if(weeks < 52 || weeks > 53) throw new Error('weekly bill counted ' + weeks + ' times');
  });
  test('joint bills: income split follows net pay, shares total one', () => {
    fresh(2026);
    Y.people = [person({id:'A', name:'A', gross:60000}), person({id:'B', name:'B', gross:30000})];
    Y.bills = [{id:'1', name:'Rent', freq:'Monthly', amount:1000, holder:'Joint', kind:'bill'}];
    const js = jointShares(), nets = Y.people.map(p => calcTax(p, Y.taxBands).netMonthly);
    near(js.shares.reduce((a, b) => a + b, 0), 1, 1e-9); near(js.shares[0], nets[0] / (nets[0] + nets[1]), 1e-9);
  });
  test('joint bills: "even disposable income" leaves everyone level', () => {
    fresh(2026);
    Y.people = [person({id:'A', name:'A', gross:60000}), person({id:'B', name:'B', gross:30000})];
    // the joint bill has to be large enough for levelling to be possible: nobody can pay more than all of it
    Y.bills = [{id:'1', name:'Rent', freq:'Monthly', amount:3000, holder:'Joint', kind:'bill'}, {id:'2', name:'Car', freq:'Monthly', amount:200, holder:'A', kind:'bill'}];
    Y.splitMode = 'disposable';
    const js = jointShares(), nets = Y.people.map(p => calcTax(p, Y.taxBands).netMonthly), bt = billTotals('bill'), sp = savingsSplit();
    if(js.capped) throw new Error('the split was capped, so this fixture cannot test levelling');
    const left = Y.people.map((p, i) => nets[i] - (bt.joint/12) * js.shares[i] - (bt.byHolder[p.name]||0)/12 - sp.rows[i].total);
    near(left[0], left[1], 0.01);
  });
  test('household: left over is take-home minus bills minus savings', () => {
    fresh(2026);
    Y.people = [person({gross:60000})];
    Y.bills = [{id:'1', name:'Rent', freq:'Monthly', amount:1000, holder:'Joint', kind:'bill'}, {id:'2', name:'Save', freq:'Monthly', amount:200, holder:'Joint', kind:'savings'}];
    const H = household(); near(H.left, H.net - 1200);
  });

  /* ---------------- disposable income ---------------- */
  test('a new year starts with the maternity planner on and an empty disposable-income tracker', () => {
    fresh(2026);
    same(Y.maternity.enabled, true);
    same(Y.disposable, {items:[], entries:[]});
  });
  test('disposable: a subscription costs its yearly total over 12, whatever it is charged by', () => {
    near(dispMonthly({amount:18, freq:'Monthly'}), 18);
    near(dispMonthly({amount:99, freq:'Annual'}), 8.25);
    near(dispMonthly({amount:10, freq:'Weekly'}), 520/12);
    near(dispMonthly({amount:30, freq:'Quarterly'}), 10);
  });
  test('disposable: the household has its spare money, less subscriptions, less what was logged that month', () => {
    fresh(2026);
    Y.people = [person({gross:60000})];
    Y.bills = [{id:'1', name:'Rent', freq:'Monthly', amount:1000, holder:'Joint', kind:'bill'}, {id:'2', name:'Save', freq:'Monthly', amount:200, holder:'Joint', kind:'savings'}];
    Y.disposable.items = [{id:'s', name:'Netflix', amount:18, freq:'Monthly', who:'Joint'}, {id:'t', name:'Prime', amount:96, freq:'Annual', who:'Joint'}];
    Y.disposable.entries = [{id:'a', date:'2026-09-03', what:'Lunch', category:'Eating out', who:'Joint', amount:64},
                            {id:'b', date:'2026-09-20', what:'Chipper', category:'Takeaways', who:'Joint', amount:40.5},
                            {id:'c', date:'2026-08-30', what:'Not this month', category:'Eating out', who:'Joint', amount:999}];
    const H = household(), S = disposableSummary('2026-09').household;
    near(S.spare, H.left);
    near(S.subs, 26);
    near(S.spent, 104.5);
    near(S.left, H.left - 26 - 104.5);
    near(disposableSummary('2026-08').household.spent, 999);
    near(disposableSummary('2026-07').household.spent, 0);
  });
  test('disposable: per person - own items plus a share of Joint ones, and the people add up to the household', () => {
    fresh(2026);
    Y.people = [person({id:'a', name:'A', gross:60000}), person({id:'b', name:'B', gross:30000})];
    Y.bills = [{id:'1', name:'Rent', freq:'Monthly', amount:1000, holder:'Joint', kind:'bill'}, {id:'2', name:'Phone', freq:'Monthly', amount:40, holder:'A', kind:'bill'},
               {id:'3', name:'Save', freq:'Monthly', amount:100, holder:'Joint', kind:'savings'}];
    Y.disposable.items = [{id:'s', name:'Gym', amount:40, freq:'Monthly', who:'A'}, {id:'t', name:'Netflix', amount:20, freq:'Monthly', who:'Joint'}];
    Y.disposable.entries = [{id:'a', date:'2026-09-05', what:'Dinner', category:'Eating out', who:'Joint', amount:100},
                            {id:'b', date:'2026-09-06', what:'Coffee', category:'Coffee & snacks', who:'A', amount:30},
                            {id:'c', date:'2026-09-07', what:'Pints', category:'Drinks & nights out', who:'B', amount:50},
                            {id:'d', date:'2026-08-07', what:'Last month', category:'Eating out', who:'B', amount:999}];
    const S = disposableSummary('2026-09'), sh = jointShares().shares, [ra, rb] = S.rows;
    near(ra.spentOwn, 30); near(ra.spentShared, 100*sh[0]); near(ra.spent, 30 + 100*sh[0]);
    near(rb.spent, 50 + 100*sh[1]);
    near(ra.subs, 40 + 20*sh[0]); near(rb.subs, 20*sh[1]);
    near(ra.spare + rb.spare, S.household.spare, 0.01, 'spare money adds up to what the household has left');
    near(ra.left + rb.left, S.household.left, 0.01, 'what is left adds up');
    near(ra.spent + rb.spent, S.household.spent);
    // the same spare money the Bills page shows each person as "left over", before any of this
    const nets = Y.people.map(p => calcTax(p, Y.taxBands).netMonthly), bt = billTotals('bill'), sp = savingsSplit();
    near(ra.spare, nets[0] - bt.joint/12*sh[0] - 40 - sp.rows[0].total);
  });
  test('disposable: categories are totalled biggest first, and something for someone who has gone still counts for the household', () => {
    fresh(2026);
    Y.people = [person({gross:60000})];
    Y.disposable.entries = [{id:'a', date:'2026-09-05', category:'Takeaways', who:'Joint', amount:30}, {id:'b', date:'2026-09-09', category:'Eating out', who:'Joint', amount:80},
                            {id:'c', date:'2026-09-12', category:'Takeaways', who:'Joint', amount:25}, {id:'d', date:'2026-09-14', category:'Gifts', who:'Ghost', amount:10}];
    const S = disposableSummary('2026-09');
    same(S.byCategory.map(c => [c.name, c.amount, c.count]), [['Eating out', 80, 1], ['Takeaways', 55, 2], ['Gifts', 10, 1]]);
    near(S.stray, 10); near(S.household.spent, 145);
    same(S.entries.map(e => e.date), ['2026-09-14', '2026-09-12', '2026-09-09', '2026-09-05']);
  });
  test('disposable: the month shown is this one, or else the latest month that has anything logged', () => {
    fresh(2026);
    const now = monthKey(new Date());
    same(dispDefaultMonth(), now);                                              // nothing logged at all
    Y.disposable.entries = [{id:'a', date:'2026-03-02', category:'Gifts', who:'Joint', amount:5}, {id:'b', date:'2026-05-02', category:'Gifts', who:'Joint', amount:5}];
    same(dispDefaultMonth(), '2026-05');
    Y.disposable.entries.push({id:'c', date:iso(new Date()), category:'Gifts', who:'Joint', amount:5});
    same(dispDefaultMonth(), now);
    same(dispMonths()[0] >= dispMonths()[dispMonths().length-1], true);        // newest first
  });
  test('disposable: restoring tidies up entries and subscriptions', () => {
    fresh(2026);
    Y.disposable = {items:[{name:'X', amount:'12', freq:'Fortnightly-ish'}], entries:[{date:'2026-09-01', amount:'5.5', category:'Nonsense'}]};
    migrate(Y);
    same([Y.disposable.items[0].amount, Y.disposable.items[0].freq, Y.disposable.items[0].who, !!Y.disposable.items[0].id], [12, 'Monthly', 'Joint', true]);
    same([Y.disposable.entries[0].amount, Y.disposable.entries[0].category, Y.disposable.entries[0].who, Y.disposable.entries[0].what], [5.5, 'Other', 'Joint', '']);
    Y.disposable = undefined; migrate(Y); same(Y.disposable, {items:[], entries:[]});
  });

  /* ---------------- savings goals, projections, reliefs ---------------- */
  test('a goal needs the remaining amount spread over the months left', () => {
    near(goalFigures({target:2400, saved:400, due:iso(addMonths(new Date(), 10))}).monthly, 200);
    near(goalFigures({target:100, saved:100, due:iso(addMonths(new Date(), 10))}).monthly, 0);
  });
  test('savings projection with no growth', () => {
    fresh(2026);
    Y.savings = {startDate:iso(new Date()), months:12, growthPct:0, accounts:[{name:'A', opening:1000, monthly:100, adjust:{}}]};
    near(projectSavings()[12].total, 2200);
  });
  test('health expenses: 20% of the cost less what the insurer paid, per receipt', () => {
    fresh(2026);
    Y.reliefs.health = [{amount:100, refunded:300}, {amount:200, refunded:0}];     // an oversized refund cancels only its own receipt
    near(reliefTotals().healthRelief, 40);
  });
  test('remote working: 30% of the share of costs for the days worked at home, at the top rate', () => {
    fresh(2026);
    Y.people = [person({gross:80000})];
    Y.reliefs.remote = {days:365, elec:600, heat:400, broadband:300, share:100};
    const R = reliefTotals();
    near(R.eligible, 1300); near(R.remoteDeduction, 390); near(R.remoteSaving, 390 * 0.4);
  });
  test('tuition fees: 20% above the disregard, with 7,000 of fees counted per course', () => {
    near(tuitionRelief({type:'full', fees:5000}), 400);      // (5,000 - 3,000) x 20%
    near(tuitionRelief({type:'part', fees:2000}), 100);      // (2,000 - 1,500) x 20%
    near(tuitionRelief({type:'full', fees:10000}), 800);     // capped at 7,000: (7,000 - 3,000) x 20%
    near(tuitionRelief({type:'full', fees:2000}), 0);        // inside the disregard
  });
  test('pension relief limits by age (percentage of earnings)', () => {
    same([29, 35, 45, 52, 57, 61].map(pensionLimitPct), [15, 20, 25, 30, 35, 40]);
  });

  /* ---------------- loans and mortgages ---------------- */
  test('mortgage payment matches the annuity formula', () => {
    near(mortPayment(300000, 4, 360, '12'), 1432.25);        // 300,000 at 4% over 30 years, monthly
    near(mortPayment(120000, 0, 120, '12'), 1000);
  });
  test('a loan clears in its term and overpaying saves interest', () => {
    const L = {opening:10000, rate:5, freq:'Monthly', startDate:'2026-01-01', endDate:'2027-01-01', repayment:0, proposedRepayment:0};
    L.repayment = calcRepayment(L);
    const base = amortise(L, false);
    same([base.payments, base.cleared], [12, true]);
    const more = Object.assign({}, L, {proposedRepayment:L.repayment + 100});
    const o = amortise(more, false), p = amortise(more, true);
    if(!(p.interest < o.interest)) throw new Error('overpaying did not reduce interest');
    if(!(p.payments <= o.payments)) throw new Error('overpaying did not shorten the loan');
  });

  /* ---------------- budget tracker ---------------- */
  test('tracker: forgiving amounts', () => {
    same(['18k', '18.5k', '1,250', '€18 000', '18000', '2.50', '', 'abc', null, '-5'].map(parseAmount),
         [18000, 18500, 1250, 18000, 18000, 2.5, 0, 0, 0, -5]);
  });
  test('tracker: forecast is the higher of budget and spend, until an item is ticked off', () => {
    const p = trackerNewProject('T');
    p.funding = [{id:'f', name:'Savings', amount:2000}];
    p.sections = [{id:'s1', name:'One', open:true, items:[
      {id:'a', name:'A', budget:1000, actual:400, done:false},   // not finished: counts at its budget, 1,000
      {id:'b', name:'B', budget:500,  actual:700, done:false},   // over already: counts at what is spent, 700
      {id:'c', name:'C', budget:300,  actual:250, done:true}]}]; // finished: counts at what was paid, 250
    const t = trackerTotals(p);
    near(t.budget, 1800); near(t.actual, 1350); near(t.forecast, 1950); near(t.toPay, 600);
    near(t.funds, 2000); near(t.headroom, 50); near(t.variance, -150);
  });
  test('tracker: totals by stage add up to the project', () => {
    const p = trackerFromTemplate('renovation');
    p.sections[0].items[0].budget = 500; p.sections[1].items[0].budget = 700; p.sections[1].items[0].actual = 650;
    const t = trackerTotals(p);
    near(t.stages.reduce((s, x) => s + x.budget, 0), t.budget); near(t.budget, 1200); near(t.actual, 650);
  });
  test('tracker: a template gives stages and funding with nothing priced yet', () => {
    TRACKER_TEMPLATES.forEach(t => {
      const p = trackerFromTemplate(t.key);
      if(!p.sections.length || !p.funding.length) throw new Error(t.key + ' has no stages or funding');
      near(trackerTotals(p).budget, 0);
      if(new Set(p.sections.flatMap(s => s.items.map(i => i.id))).size !== p.sections.reduce((n, s) => n + s.items.length, 0)) throw new Error('item ids clash');
    });
  });
  test('tracker: files from the standalone tool import, in any of its shapes', () => {
    const full = trackerNormalise({v:2, active:'p2', projects:[{id:'p1', name:'A', sections:[]}, {id:'p2', name:'B', currency:'£', funding:[{name:'Loan', amount:'5000'}], sections:[{name:'S', items:[{name:'I', budget:'100'}]}]}]});
    same([full.projects.length, full.active, full.projects[1].currency, full.projects[1].funding[0].amount, full.projects[1].sections[0].items[0].budget, full.projects[1].sections[0].open], [2, 'p2', '£', 5000, 100, true]);
    same(trackerNormalise({projects:[{sections:[{items:[{budget:'3k', actual:'1,250'}]}], funding:[{amount:'25k'}]}]}).projects[0].sections[0].items.map(i => [i.budget, i.actual]), [[3000, 1250]]);
    const bare = trackerNormalise({name:'Reno', sections:[{name:'S', items:[]}]});
    same([bare.projects.length, bare.projects[0].name, bare.projects[0].currency], [1, 'Reno', '€']);
    same(trackerNormalise({nonsense:true}), null); same(trackerNormalise(null), null); same(trackerNormalise('text'), null);
  });
  test('tracker: adding projects keeps the ones already there and fixes clashing ids', () => {
    fresh(2026);
    DB.tracker = trackerBlank();
    trackerAdd([{id:'x', name:'First', currency:'€', funding:[], sections:[]}]);
    trackerAdd([{id:'x', name:'Second', currency:'€', funding:[], sections:[]}]);
    same(DB.tracker.projects.map(p => p.name), ['First', 'Second']);
    if(DB.tracker.projects[0].id === DB.tracker.projects[1].id) throw new Error('ids still clash');
    same(trackerProject().name, 'Second');
  });
  test('tracker: the spreadsheet export lists items and totals', () => {
    const p = trackerNewProject('Wedding');
    p.funding = [{id:'f', name:'Savings', amount:500}];
    p.sections = [{id:'s', name:'Venue', open:true, items:[{id:'i', name:'Deposit', budget:300, actual:200, done:true}]}];
    const rows = trackerCsvRows(p);
    same(rows[2], ['Stage', 'Item', 'Budget', 'Spent', 'Variance', 'Done']);
    same(rows[3], ['Venue', 'Deposit', 300, 200, 100, 'yes']);
    same(rows.filter(r => r[0] === 'HEADROOM')[0][2], 300);          // 500 funding - 200 forecast (ticked off, so what was paid)
  });
  test('tracker: money formatting', () => {
    same([trackerMoney(1234.6, '€'), trackerMoney(-50, '£'), trackerMoneyK(25000, '€'), trackerMoneyK(12500, '€'), trackerMoneyK(-12500, '€'), trackerMoneyK(900, '€')],
         ['€1,235', '-£50', '€25k', '€12.5k', '-€12.5k', '€900']);
    same([trackerAmountText(0), trackerAmountText(1250), trackerAmountText(2.5)], ['', '1,250', '2.5']);
  });

  /* ---------------- formatting ---------------- */
  test('amounts: a tiny negative shows as zero, a real one keeps its sign', () => {
    same([fmt(-0.3, 0), fmt(-5.4, 0), fmt(1234.5)], ['€0', '-€5', '€1,234.50']);
  });

  return results;
}
